version: '3'

services:
  db:
    image: postgres:15
    container_name: bot_db
    env_file: .env-prod

  redis:
    image: redis:7
    container_name: bot_redis

  napominalka_bot:
    build:
      context: .
    env_file:
      - .env-prod
    depends_on:
      - db
      - redis
    command: [ "/napominalka_bot/docker/app.sh" ]
