version: '3'

services:
  db:
    image: postgres:15
    container_name: bot_db
    env_file: .env-prod
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    container_name: bot_redis
    volumes:
      - redis_data:/usr/local/etc/redis

  napominalka_bot:
    build:
      context: .
    ports:
      - "8080:8080"
    env_file:
      - .env-prod
    depends_on:
      - db
      - redis
    command: [ "/napominalka_bot/docker/app.sh" ]


volumes:
  postgres_data:
  redis_data: