version: '3'

volumes:
  postgresql_volume:

services:
  db:
    image: postgres:15
    container_name: bot_db
    env_file: .env
    restart: always

  redis:
    image: redis:7
    container_name: bot_redis
    restart: always

  napominalka_bot:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: [ "/napominalka_bot/docker/app.sh" ]
    restart: always

