"""final.

Revision ID: bb66924a8261
Revises: 9ff973ce155c
Create Date: 2023-09-18 20:23:21.568903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb66924a8261'
down_revision: Union[str, None] = '9ff973ce155c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduledate', 'reminder_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduledate', sa.Column('reminder_text', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
