"""Add new tables2

Revision ID: d582393732fa
Revises: 20ac07a51496
Create Date: 2023-09-08 12:53:13.339428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd582393732fa'
down_revision: Union[str, None] = '20ac07a51496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduling_date',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_date', sa.Date(), unique=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduling_time',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_time', sa.Time()),
    sa.Column('schedule_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_date'], ['scheduling_date.schedule_date'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduling_time')
    op.drop_table('scheduling_date')
    # ### end Alembic commands ###
