name: Run linter checks

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  run_linters_tests:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        continue-on-error: true
      - name: Lint with flake8
        run: |
          flake8 .
      - name: Lint with black
        run: |
          black . --check --diff
          
